#!/bin/bash

main() {
    clear
    echo -e "Welcome to the MacSploit Experience!"
    echo -e "Install Script Version 2.3"

    # Download Latest Roblox
    echo -e "Downloading Latest Roblox..."
    [ -f ./RobloxPlayer.zip ] && rm ./RobloxPlayer.zip
    curl -s "http://setup.rbxcdn.com/mac/version-ecb0dc61c2ff4160-RobloxPlayer.zip" -o "./RobloxPlayer.zip"

    # Install Latest Roblox
    echo -n "Installing Latest Roblox... "
    [ -d "/Applications/Roblox.app" ] && rm -rf "/Applications/Roblox.app"
    unzip -o -q "./RobloxPlayer.zip"
    mv ./RobloxPlayer.app /Applications/Roblox.app
    rm ./RobloxPlayer.zip
    echo -e "Done."

    # Download MacSploit
    echo -e "Downloading MacSploit..."
    curl -s "https://git.abyssdigital.xyz/main/macsploit.zip" -o "./MacSploit.zip"

    # Install MacSploit
    echo -n "Installing MacSploit... "
    unzip -o -q "./MacSploit.zip"
    echo -e "Done."

    # Update dylib
    echo -n "Updating Dylib..."
    curl -Os "https://git.abyssdigital.xyz/main/macsploit.dylib"
    curl -Os "https://git.abyssdigital.xyz/main/libdiscord-rpc.dylib"
    echo -e " Done."

    # Patching Roblox
    echo -e "Patching Roblox..."
    if [ -f ./macsploit.dylib ]; then
        mv ./macsploit.dylib "/Applications/Roblox.app/Contents/MacOS/macsploit.dylib"
    else
        echo "Error: macsploit.dylib is missing."
        exit 1
    fi

    if [ -f ./libdiscord-rpc.dylib ]; then
        mv ./libdiscord-rpc.dylib "/Applications/Roblox.app/Contents/MacOS/libdiscord-rpc.dylib"
    else
        echo "Warning: libdiscord-rpc.dylib is missing. Skipping..."
    fi

    ./insert_dylib "/Applications/Roblox.app/Contents/MacOS/macsploit.dylib" "/Applications/Roblox.app/Contents/MacOS/RobloxPlayer" --strip-codesig --all-yes
    mv "/Applications/Roblox.app/Contents/MacOS/RobloxPlayer_patched" "/Applications/Roblox.app/Contents/MacOS/RobloxPlayer"
    rm -r "/Applications/Roblox.app/Contents/MacOS/RobloxPlayerInstaller.app"
    rm ./insert_dylib

    # Install MacSploit App
    echo -n "Installing MacSploit App... "
    [ -d "/Applications/MacSploit.app" ] && rm -rf "/Applications/MacSploit.app"
    mv ./MacSploit.app /Applications/MacSploit.app
    rm ./MacSploit.zip
    echo -e "Done."

    # Installation Complete
    echo -e "Install Complete! Developed by Nexus42!"
    exit
}

main
